name: NRI
channels:
  - projectchrono
  - plotly
  - conda-forge
dependencies:
  - python=3.7            # can't go 3.8 for pychrono
  - jupyterlab=2*       
  - pychrono=5.0.0        
  - plotly=4.14.*
  - matplotlib
  - scipy
  - numpy
  - ipywidgets>7.5        # for interactivity
  - shapely=1.7.0         # for shape objects and overlap calculation - compatable with py 3.7
  - cma                   # CMA-ES optimizer
  - xeus-python           # for debugger extension
  - ptvsd                 # ford debugger extension
  - nodejs                # to install jupyterlab extensions
  pip:
      - landscapes        # test functionsfor optimizer evaluation
