name: NRI
channels:
  - plotly
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - shapely=1.7.0
  - ipykernel=5.1.4
  - ipython=7.13.0
  - ipywidgets=7.5.1
  - numpy=1.18.1
  - numpy-base=1.18.1
  - python=3.8.2
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - sympy=1.5.1
  - plotly=4.5.4=py_0
  - jupyterlab-plotly-extension=1.0.0


