#!/bin/bash

# Install a JupyterLab extension for demonstration purposes
jupyter labextension install @jupyter-widgets/jupyterlab-manager
jupyter labextension install jupyterlab-plotly
jupyter labextension install plotlywidget
